# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(985, 643)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(985, 643))
        Form.setMaximumSize(QtCore.QSize(985, 643))
        Form.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("C:/Users/dcristian/.designer/screenshotMaker/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.actionButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionButton.setFont(font)
        self.actionButton.setObjectName("actionButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.actionButton)
        self.popupIdField = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.popupIdField.sizePolicy().hasHeightForWidth())
        self.popupIdField.setSizePolicy(sizePolicy)
        self.popupIdField.setEditable(True)
        self.popupIdField.setCurrentText("")
        self.popupIdField.setMaxVisibleItems(50)
        self.popupIdField.setDuplicatesEnabled(False)
        self.popupIdField.setModelColumn(0)
        self.popupIdField.setObjectName("popupIdField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.popupIdField)
        self.verticalLayout.addLayout(self.formLayout)
        self.images = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.images.sizePolicy().hasHeightForWidth())
        self.images.setSizePolicy(sizePolicy)
        self.images.setMinimumSize(QtCore.QSize(965, 566))
        self.images.setMaximumSize(QtCore.QSize(965, 566))
        self.images.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.images.setTabsClosable(False)
        self.images.setMovable(True)
        self.images.setTabBarAutoHide(True)
        self.images.setObjectName("images")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.labelTab1 = QtWidgets.QLabel(self.tab1)
        self.labelTab1.setGeometry(QtCore.QRect(0, 0, 960, 540))
        self.labelTab1.setMinimumSize(QtCore.QSize(960, 540))
        self.labelTab1.setMaximumSize(QtCore.QSize(960, 540))
        self.labelTab1.setAcceptDrops(False)
        self.labelTab1.setAutoFillBackground(False)
        self.labelTab1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelTab1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelTab1.setText("")
        self.labelTab1.setObjectName("labelTab1")
        self.saveButton1 = QtWidgets.QPushButton(self.tab1)
        self.saveButton1.setEnabled(False)
        self.saveButton1.setGeometry(QtCore.QRect(0, 2, 85, 23))
        self.saveButton1.setObjectName("saveButton1")
        self.images.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.labelTab2 = QtWidgets.QLabel(self.tab2)
        self.labelTab2.setGeometry(QtCore.QRect(0, 0, 960, 540))
        self.labelTab2.setMinimumSize(QtCore.QSize(960, 540))
        self.labelTab2.setMaximumSize(QtCore.QSize(960, 540))
        self.labelTab2.setAcceptDrops(False)
        self.labelTab2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelTab2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelTab2.setText("")
        self.labelTab2.setObjectName("labelTab2")
        self.saveButton2 = QtWidgets.QPushButton(self.tab2)
        self.saveButton2.setEnabled(False)
        self.saveButton2.setGeometry(QtCore.QRect(85, 2, 85, 23))
        self.saveButton2.setDefault(False)
        self.saveButton2.setFlat(False)
        self.saveButton2.setObjectName("saveButton2")
        self.images.addTab(self.tab2, "")
        self.verticalLayout.addWidget(self.images)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.images.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "    "))
        self.actionButton.setText(_translate("Form", "SNAPSHOT"))
        self.saveButton1.setText(_translate("Form", "Save"))
        self.images.setTabText(self.images.indexOf(self.tab1), _translate("Form", "Screenshot 1"))
        self.saveButton2.setText(_translate("Form", "Save"))
        self.images.setTabText(self.images.indexOf(self.tab2), _translate("Form", "Screenshot 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

